@startuml
left to right direction
class Utilisateur {

}
class Agence {
  -agenceId: Integer
}
Utilisateur "*" -- "*" Agence

class UtilisateurAgence {
- role: String
}
(Utilisateur,Agence) -- UtilisateurAgence
@enduml