@startuml
left to right direction
class Utilisateur {

}
class Agence {
  -agenceId: int
}
Utilisateur "*" -- "*" Agence

enum Role {
  {static} +Secretaire
  {static} +Accueil
}

class UtilisateurAgence {
- role: Role
+ getRole(): Optional<Role>
+ hasRole(role: Role): boolean
+ isSameAgence(agenceId: int): boolean
}
(Utilisateur,Agence) -- UtilisateurAgence
UtilisateurAgence --> Role
@enduml