@startuml
skinparam linetype ortho
map utilisateur1 {
}

map agence1 {
  id => 1
}

map agence2 {
  id => 2
}

map Secretaire {
}

map Accueil {
}

map u1a1 {
  role *-> Secretaire
}

map u1a2 {
  role *-> Accueil
}

utilisateur1 -- agence1
utilisateur1 -- agence2

(utilisateur1, agence1) -- u1a1
(utilisateur1, agence2) -- u1a2
@enduml